name: reuseable-workflow

on:
  workflow_call:
    inputs:
      ingress-url:
        required: true
        description: 'Provide the Ingress URL'
        type: string

# 1. 'jobs:' moved to the root level
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      # 2. 'env' block removed because it referenced 'needs' from the parent workflow
      - name: Run curl test
        # 3. Accessed the variable using 'inputs.ingress-url'
        run: |
          curl ${{ inputs.ingress-url }} -s -k | jq -r .status | grep -i live